/* empty css                      */import{a as E,S as h,i as a}from"./assets/vendor-hwdYKDic.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const P="48862394-3b6e651acc095b3f3f471775f",q="https://pixabay.com/api/";async function $(r,o=1,t=40){try{const i=await E.get(q,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t}});return{images:i.data.hits,totalHits:i.data.totalHits}}catch(i){throw console.error("Помилка при отриманні зображень:",i),i}}let g=null;function m(r,o=!1){const t=document.querySelector("#gallery"),i=r.map(({webformatURL:e,largeImageURL:s,tags:n,likes:w,views:v,comments:S,downloads:b})=>`<div class="gallery-item">
          <a href="${s}" class="gallery-link">
            <img src="${e}" alt="${n}" loading="lazy"/>
          </a>
          <div class="image-info">
            <p><strong>Likes:</strong> ${w}</p>
            <p><strong>Views:</strong> ${v}</p>
            <p><strong>Comments:</strong> ${S}</p>
            <p><strong>Downloads:</strong> ${b}</p>
          </div>
        </div>`).join("");o?t.insertAdjacentHTML("beforeend",i):t.innerHTML=i,g?g.refresh():g=new h("#gallery a",{captionsData:"alt",captionDelay:250})}const u=document.querySelector(".search-form"),H=document.querySelector("#gallery"),f=document.querySelector("#loader"),l=document.querySelector("#load-more");let p=new h(".gallery a"),c=1,d="";const y=40;a.settings({resetOnHover:!0});async function L(r,o=1){o===1&&a.info({title:"Info",message:"Loading...",position:"topRight",timeout:!1}),f.classList.remove("hidden");try{return await $(r,o,y)}catch(t){throw console.error("Error fetching images:",t),t}finally{f.classList.add("hidden"),a.destroy()}}u.addEventListener("submit",async r=>{r.preventDefault();const o=u.searchQuery.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}d=o,c=1,H.innerHTML="",l.classList.add("hidden");try{const{images:t,totalHits:i}=await L(d,c);if(!t||t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}m(t,!1),p.refresh(),t.length>0&&t.length===y&&l.classList.remove("hidden")}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});l.addEventListener("click",async()=>{c+=1;try{const{images:r}=await L(d,c);if(!r||r.length===0){a.error({title:"Error",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),l.classList.add("hidden");return}m(r,!0),p.refresh(),smoothScroll()}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
