/* empty css                      */import{a as P,S as m,i as a}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const q="48862394-3b6e651acc095b3f3f471775f",H="https://pixabay.com/api/";async function R(r,e=1,s=40){try{const i=await P.get(H,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,perPage:s}});return{images:i.data.hits,totalHits:i.data.totalHits}}catch(i){throw console.error("Помилка при отриманні зображень:",i),i}}let g=null;function p(r){const e=document.querySelector("#gallery");e.innerHTML="";const s=r.map(({webformatURL:i,largeImageURL:t,tags:o,likes:c,views:v,comments:S,downloads:b})=>`<div class="gallery-item">
          <a href="${t}" class="gallery-link">
            <img src="${i}" alt="${o}" loading="lazy"/>
          </a>
          <div class="image-info">
            <p><strong>Likes:</strong> ${c}</p>
            <p><strong>Views:</strong> ${v}</p>
            <p><strong>Comments:</strong> ${S}</p>
            <p><strong>Downloads:</strong> ${b}</p>
          </div>
        </div>`).join("");e.innerHTML=s,g?g.refresh():g=new m("#gallery a",{captionsData:"alt",captionDelay:250})}const u=document.querySelector(".search-form"),E=document.querySelector("#gallery"),f=document.querySelector("#loader"),n=document.querySelector("#load-more");let y=new m(".gallery a"),l=1,d="";const h=40;a.settings({resetOnHover:!0});async function L(r,e){a.info({title:"Info",message:"Loading...",position:"topRight",timeout:!1}),f.classList.remove("hidden");try{const{images:s,totalHits:i}=await R(r,e,h);return{images:s,totalHits:i}}catch(s){throw console.error("Error fetching images:",s),s}finally{f.classList.add("hidden"),a.destroy()}}u.addEventListener("submit",async r=>{if(r.preventDefault(),d=u.searchQuery.value.trim(),!d&&!query){a.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}l=1,E.innerHTML="",n.classList.add("hidden");try{const{images:e,totalHits:s}=await L(d,l);if(!e||e.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p(e),y.refresh(),w(),l*h>=s?(a.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"}),n.classList.add("hidden")):n.classList.remove("hidden")}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});n.addEventListener("click",async()=>{l++;try{const{images:r,totalHits:e}=await L(d,l);if(!r||r.length===0){a.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"}),n.classList.add("hidden");return}p(r),y.refresh(),w(),l*h>=e&&(a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.classList.add("hidden"))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});function w(){const r=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
