/* empty css                      */import{a as p,S as u,i as n}from"./assets/vendor-hwdYKDic.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y="48862394-3b6e651acc095b3f3f471775f",h="https://pixabay.com/api/";async function L(o){try{return(await p.get(h,{params:{key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(r){throw console.error("Помилка при отриманні зображень:",r),r}}let l=null;function w(o){const r=document.querySelector("#gallery");r.innerHTML="";const s=o.map(({webformatURL:a,largeImageURL:e,tags:t,likes:i,views:f,comments:m,downloads:d})=>`<div class="gallery-item">
          <a href="${e}" class="gallery-link">
            <img src="${a}" alt="${t}" loading="lazy"/>
          </a>
          <div class="image-info">
            <p><strong>Likes:</strong> ${i}</p>
            <p><strong>Views:</strong> ${f}</p>
            <p><strong>Comments:</strong> ${m}</p>
            <p><strong>Downloads:</strong> ${d}</p>
          </div>
        </div>`).join("");r.innerHTML=s,l?l.refresh():l=new u("#gallery a",{captionsData:"alt",captionDelay:250})}const c=document.querySelector(".search-form"),v=document.querySelector("#gallery"),g=document.querySelector("#loader");let b=new u(".gallery a");n.settings({resetOnHover:!0});async function S(o){n.info({title:"Info",message:"Loading...",position:"topRight",timeout:!1}),g.classList.remove("hidden");try{return await L(o)}catch(r){throw console.error("Error fetching images:",r),r}finally{g.classList.add("hidden"),n.destroy()}}c.addEventListener("submit",async o=>{o.preventDefault();const r=c.searchQuery.value.trim();if(!r){n.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}try{const s=await S(r);if(!s||s.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}v.innerHTML="",w(s),b.refresh()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
